// <auto-generated />
using System;
using DischargeDisposition_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DischargeDisposition_Backend.Migrations.Hospital
{
    [DbContext(typeof(HospitalDbContext))]
    partial class HospitalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.AuthorizationTracking", b =>
                {
                    b.Property<long>("AuthorizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuthorizationId"));

                    b.Property<string>("DenialReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExternalAuthorizationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("InsuranceAuthorizationRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("PayerId")
                        .HasColumnType("int");

                    b.Property<int>("ReferralId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("AuthorizationId");

                    b.HasIndex("ExternalAuthorizationId")
                        .IsUnique();

                    b.HasIndex("PatientId");

                    b.HasIndex("PayerId");

                    b.HasIndex("ReferralId")
                        .IsUnique();

                    b.ToTable("AuthorizationTrackings");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.DelayReasonCode", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("ReasonName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DelayReasonCodes");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.Department", b =>
                {
                    b.Property<byte>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("DeptId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DeptId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.DispositionDecision", b =>
                {
                    b.Property<int>("DecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DecisionId"));

                    b.Property<int>("ClinicianId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DecisionDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("DepartmentId")
                        .HasColumnType("tinyint");

                    b.Property<int>("DispositionTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpectedTransitionDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("DecisionId");

                    b.HasIndex("ClinicianId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DispositionTypeId");

                    b.HasIndex("PatientId");

                    b.ToTable("DispositionDecisions");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.DispositionType", b =>
                {
                    b.Property<int>("DispositionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DispositionTypeId"));

                    b.Property<string>("DispositionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DispositionTypeId");

                    b.ToTable("DispositionTypes");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.LengthOfStayTracking", b =>
                {
                    b.Property<long>("TrackingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TrackingId"));

                    b.Property<DateTime>("LastCalculatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<short>("VarianceDays")
                        .HasColumnType("smallint");

                    b.HasKey("TrackingId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("LengthOfStayTrackings");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateTime>("ActualDischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("DeptId")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ExpectedDischargeDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mrn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte>("departmentDeptId")
                        .HasColumnType("tinyint");

                    b.HasKey("PatientId");

                    b.HasIndex("Mrn")
                        .IsUnique();

                    b.HasIndex("departmentDeptId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.PatientDelay", b =>
                {
                    b.Property<int>("PatientDelayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientDelayId"));

                    b.Property<byte>("DelayReasonId")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("ReportedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PatientDelayId");

                    b.HasIndex("DelayReasonId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ReportedBy");

                    b.HasIndex("UserId");

                    b.ToTable("PatientDelays");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.Payer", b =>
                {
                    b.Property<int>("PayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayerId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PayerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("PayerId");

                    b.HasIndex("PayerName")
                        .IsUnique();

                    b.ToTable("Payers");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.PostAcuteProvider", b =>
                {
                    b.Property<int>("ProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProviderId"));

                    b.Property<string>("AddressLine")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("DispositionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProviderId");

                    b.HasIndex("DispositionTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("PostAcuteProviders");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.Referral", b =>
                {
                    b.Property<int>("ReferralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReferralId"));

                    b.Property<int>("CareManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ReferralId");

                    b.HasIndex("CareManagerId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProviderId");

                    b.ToTable("Referrals");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.Role", b =>
                {
                    b.Property<byte>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("DeptId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte>("RoleId")
                        .HasColumnType("tinyint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.HasIndex("DeptId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.AuthorizationTracking", b =>
                {
                    b.HasOne("DischargeDisposition_Backend.Hospital.Models.Patient", "patient")
                        .WithMany("AuthorizationTrackings")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DischargeDisposition_Backend.Hospital.Models.Payer", "payer")
                        .WithMany("AuthorizationTrackings")
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DischargeDisposition_Backend.Hospital.Models.Referral", "referral")
                        .WithOne("authorizationTrackings")
                        .HasForeignKey("DischargeDisposition_Backend.Hospital.Models.AuthorizationTracking", "ReferralId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("patient");

                    b.Navigation("payer");

                    b.Navigation("referral");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.DispositionDecision", b =>
                {
                    b.HasOne("DischargeDisposition_Backend.Hospital.Models.User", "clinician")
                        .WithMany("DispositionDecisions")
                        .HasForeignKey("ClinicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DischargeDisposition_Backend.Hospital.Models.Department", "department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DischargeDisposition_Backend.Hospital.Models.DispositionType", "dispositionType")
                        .WithMany("DispositionDecisions")
                        .HasForeignKey("DispositionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DischargeDisposition_Backend.Hospital.Models.Patient", "patient")
                        .WithMany("DispositionDecisions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("clinician");

                    b.Navigation("department");

                    b.Navigation("dispositionType");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.LengthOfStayTracking", b =>
                {
                    b.HasOne("DischargeDisposition_Backend.Hospital.Models.Patient", "patient")
                        .WithOne("lengthOfStayTracking")
                        .HasForeignKey("DischargeDisposition_Backend.Hospital.Models.LengthOfStayTracking", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("patient");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.Patient", b =>
                {
                    b.HasOne("DischargeDisposition_Backend.Hospital.Models.Department", "department")
                        .WithMany("Patients")
                        .HasForeignKey("departmentDeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.PatientDelay", b =>
                {
                    b.HasOne("DischargeDisposition_Backend.Hospital.Models.DelayReasonCode", "delayReason")
                        .WithMany()
                        .HasForeignKey("DelayReasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DischargeDisposition_Backend.Hospital.Models.Patient", "patient")
                        .WithMany("PatientDelays")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DischargeDisposition_Backend.Hospital.Models.User", "reportedUser")
                        .WithMany()
                        .HasForeignKey("ReportedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DischargeDisposition_Backend.Hospital.Models.User", null)
                        .WithMany("PatientDelays")
                        .HasForeignKey("UserId");

                    b.Navigation("delayReason");

                    b.Navigation("patient");

                    b.Navigation("reportedUser");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.PostAcuteProvider", b =>
                {
                    b.HasOne("DischargeDisposition_Backend.Hospital.Models.DispositionType", "dispositionType")
                        .WithMany("PostAcuteProviders")
                        .HasForeignKey("DispositionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DischargeDisposition_Backend.Hospital.Models.User", "user")
                        .WithMany("PostAcuteProviders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("dispositionType");

                    b.Navigation("user");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.Referral", b =>
                {
                    b.HasOne("DischargeDisposition_Backend.Hospital.Models.User", "careManager")
                        .WithMany("Referrals")
                        .HasForeignKey("CareManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DischargeDisposition_Backend.Hospital.Models.Patient", "patient")
                        .WithMany("Referrals")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DischargeDisposition_Backend.Hospital.Models.PostAcuteProvider", "provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("careManager");

                    b.Navigation("patient");

                    b.Navigation("provider");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.User", b =>
                {
                    b.HasOne("DischargeDisposition_Backend.Hospital.Models.Department", "department")
                        .WithMany("Users")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DischargeDisposition_Backend.Hospital.Models.Role", "role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");

                    b.Navigation("role");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.Department", b =>
                {
                    b.Navigation("Patients");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.DispositionType", b =>
                {
                    b.Navigation("DispositionDecisions");

                    b.Navigation("PostAcuteProviders");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.Patient", b =>
                {
                    b.Navigation("AuthorizationTrackings");

                    b.Navigation("DispositionDecisions");

                    b.Navigation("PatientDelays");

                    b.Navigation("Referrals");

                    b.Navigation("lengthOfStayTracking");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.Payer", b =>
                {
                    b.Navigation("AuthorizationTrackings");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.Referral", b =>
                {
                    b.Navigation("authorizationTrackings");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Hospital.Models.User", b =>
                {
                    b.Navigation("DispositionDecisions");

                    b.Navigation("PatientDelays");

                    b.Navigation("PostAcuteProviders");

                    b.Navigation("Referrals");
                });
#pragma warning restore 612, 618
        }
    }
}
