// <auto-generated />
using System;
using DischargeDisposition_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DischargeDisposition_Backend.Migrations.Insurance
{
    [DbContext(typeof(InsuranceDbContext))]
    partial class InsuranceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DischargeDisposition_Backend.Insurance.Models.AuthorizationDecision", b =>
                {
                    b.Property<int>("DecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DecisionId"));

                    b.Property<int>("AuthorizationRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DecisionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecisionStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DecisionId");

                    b.HasIndex("AuthorizationRequestId");

                    b.ToTable("AuthorizationDecisions");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Insurance.Models.AuthorizationRequest", b =>
                {
                    b.Property<int>("AuthorizationRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorizationRequestId"));

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestingOrganization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("AuthorizationRequestId");

                    b.HasIndex("MemberId");

                    b.ToTable("AuthorizationRequests");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Insurance.Models.CoverageRule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleId"));

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresAuthorization")
                        .HasColumnType("bit");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RuleId");

                    b.HasIndex("PlanId");

                    b.ToTable("CoverageRules");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Insurance.Models.InsuranceProvider", b =>
                {
                    b.Property<int>("InsuranceProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsuranceProviderId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("InsuranceProviderId");

                    b.HasIndex("ProviderCode")
                        .IsUnique();

                    b.ToTable("InsuranceProviders");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Insurance.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<DateTime>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MemberId");

                    b.HasIndex("PolicyNumber")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Insurance.Models.MemberCoverage", b =>
                {
                    b.Property<int>("CoverageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoverageId"));

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.HasKey("CoverageId");

                    b.HasIndex("MemberId");

                    b.HasIndex("PlanId");

                    b.ToTable("MemberCoverages");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Insurance.Models.Plan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<int>("InsuranceProviderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PlanId");

                    b.HasIndex("InsuranceProviderId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Insurance.Models.AuthorizationDecision", b =>
                {
                    b.HasOne("DischargeDisposition_Backend.Insurance.Models.AuthorizationRequest", "authorizationRequest")
                        .WithMany("AuthorizationDecisions")
                        .HasForeignKey("AuthorizationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("authorizationRequest");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Insurance.Models.AuthorizationRequest", b =>
                {
                    b.HasOne("DischargeDisposition_Backend.Insurance.Models.Member", "member")
                        .WithMany("AuthorizationRequests")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("member");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Insurance.Models.CoverageRule", b =>
                {
                    b.HasOne("DischargeDisposition_Backend.Insurance.Models.Plan", "plan")
                        .WithMany("CoverageRules")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("plan");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Insurance.Models.MemberCoverage", b =>
                {
                    b.HasOne("DischargeDisposition_Backend.Insurance.Models.Member", "member")
                        .WithMany("MemberCoverages")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DischargeDisposition_Backend.Insurance.Models.Plan", "plan")
                        .WithMany("MemberCoverages")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("member");

                    b.Navigation("plan");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Insurance.Models.Plan", b =>
                {
                    b.HasOne("DischargeDisposition_Backend.Insurance.Models.InsuranceProvider", "insuranceProvider")
                        .WithMany("Plans")
                        .HasForeignKey("InsuranceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("insuranceProvider");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Insurance.Models.AuthorizationRequest", b =>
                {
                    b.Navigation("AuthorizationDecisions");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Insurance.Models.InsuranceProvider", b =>
                {
                    b.Navigation("Plans");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Insurance.Models.Member", b =>
                {
                    b.Navigation("AuthorizationRequests");

                    b.Navigation("MemberCoverages");
                });

            modelBuilder.Entity("DischargeDisposition_Backend.Insurance.Models.Plan", b =>
                {
                    b.Navigation("CoverageRules");

                    b.Navigation("MemberCoverages");
                });
#pragma warning restore 612, 618
        }
    }
}
